# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#hero"
  weight = 10

[[main]]
 name = "Overview"
  url = "courses/math6312-sp19/"
  weight = 15


[[main]]
 name = "Syllabus"
  url = "courses/math6312-sp19/math6312-syllabus"
  weight = 20

[[main]]
  name = "Data Sets"
  url = "courses/math6312-sp19/math6312-data"
  weight = 30

[[main]]
  name = "Homework"
  url = "courses/math6312-sp19/hw"
  weight = 50

[[main]]
  name = "R Lab"
  url = "courses/math6312-sp19/rlab"
  weight = 40

# [[main]]
#   name = "Resources"
#   url = "#resources"
#   weight = 60

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70

[[math6312-sp19]]
  name = "Data Mining"
  weight = 10

[[math6312-sp19]]
  name = "R Lab"
  weight = 20

[[math6312-sp19]]
  name = "Homework"
  weight = 30
